title: Open Sales and Distribution Model - Converter Tool
email: clemens.gantert@deutschebahn.com

description: >- # this means to ignore newlines until "baseurl:"
  Open Sales and Distribution Model to simplify rail distribution.
baseurl: "/OSDM-Converter" # the subpath of your site, e.g. /blog

# url: "http://osdm.github.com"

permalink: pretty

favicon: favicon.png

fixed_navbar: top

# Build settings
remote_theme: chrisrhymes/bulma-clean-theme

# Don't publish files in the future
future: false

plugins:
  - jekyll-analytics
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  - kramdown-parser-gfm

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

markdown: kramdown