//
// Diese Datei wurde mit der JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 generiert 
// Siehe <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// �nderungen an dieser Datei gehen bei einer Neukompilierung des Quellschemas verloren. 
// Generiert: 2026.05.22 um 10:24:00 AM CEST 
//


package uk.org.netex.netex;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Type for an Implementation of an aggregate relationship by reference or value, where the contained element or reference is included in the XML as a child of the parent.
 * 
 * <p>Java-Klasse f�r containmentAggregationStructure complex type.
 * 
 * <p>Das folgende Schemafragment gibt den erwarteten Content an, der in dieser Klasse enthalten ist.
 * 
 * <pre>
 * &lt;complexType name="containmentAggregationStructure">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.netex.org.uk/netex}relationshipStructure">
 *       &lt;attribute name="modificationSet" type="{http://www.netex.org.uk/netex}ModificationSetEnumeration" default="all" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "containmentAggregationStructure")
@XmlSeeAlso({
    ValidityConditionsRelStructure.class,
    CustomerPurchaseParameterAssignmentsRelStructure.class,
    ServiceFacilitySetsRelStructure.class,
    EquipmentsRelStructure.class,
    ContractRefRelStructure.class,
    ActivationAssignmentsRelStructure.class,
    BookingArrangementsRelStructure.class,
    VehicleEquipmentsRelStructure.class,
    ControlCentresRelStructure.class,
    DeckPlanAssignmentsRelStructure.class,
    VehicleEquipmentProfilesInFrameRelStructure.class,
    ReliefPointsInFrameRelStructure.class,
    ContainedAvailabilityConditionsRelStructure.class,
    ActivationLinksInFrameRelStructure.class,
    FramesRelStructure.class,
    VehicleMeetingLinksInFrameRelStructure.class,
    RetailDevicesRelStructure.class,
    DestinationDisplayViewsRelStructure.class,
    ServicePatternsInFrameRelStructure.class,
    SingleJourneyPathsRelStructure.class,
    ParkingBaysRelStructure.class,
    OperatingDaysRelStructure.class,
    RoutingConstraintZonesInFrameRelStructure.class,
    TypesOfFareContractRelStructure.class,
    LevelsRelStructure.class,
    DecksRelStructure.class,
    VehiclesInFrameRelStructure.class,
    VehiclePoolingDriverInfosRelStructure.class,
    DataSourcesInFrameRelStructure.class,
    QuaysRelStructure.class,
    TrainElementTypesInFrameRelStructure.class,
    AccessRightParameterAssignmentsRelStructure.class,
    StopAssignmentsInFrameRelStructure.class,
    StopAreasInFrameRelStructure.class,
    TypesOfSalesOfferPackageRelStructure.class,
    InterchangeRuleTimingsRelStructure.class,
    SitePathJunctionsRelStructure.class,
    SingleJourneysRelStructure.class,
    GroupOfTimebandsRelStructure.class,
    ActivationPointsInFrameRelStructure.class,
    VehicleJourneyStopAssignmentsInFrameRelStructure.class,
    OtherDeckSpacesRelStructure.class,
    TimebandsInFrameRelStructure.class,
    JourneyPartsRelStructure.class,
    FrequencyGroupsInFrameRelStructure.class,
    FrequencyGroupsRelStructure.class,
    ActivatedEquipmentsInFrameRelStructure.class,
    TrainStopAssignmentsRelStructure.class,
    AddressesInFrameRelStructure.class,
    GroupsOfLinesInFrameRelStructure.class,
    TypesOfServiceInFrameRelStructure.class,
    TypeOfFareProductsRelStructure.class,
    SitePathJunctionsInFrameRelStructure.class,
    CoupledJourneysInFrameRelStructure.class,
    MobilityServiceRefsRelStructure.class,
    VehicleMeetingPointAssignmentsInFrameRelStructure.class,
    TypesOfFareContractEntryRelStructure.class,
    MediumApplicationInstanceRelStructure.class,
    TimingPatternsInFrameRelStructure.class,
    OperatingPeriodsRelStructure.class,
    OfferedTravelSpecificationsRelStructure.class,
    GroupsOfSingleJourneysRelStructure.class,
    VehicleMeetingPointsInSequenceRelStructure.class,
    DeckPlansRelStructure.class,
    ServiceBookingArrangementsInFrameRelStructure.class,
    AssistanceBookingServicesRelStructure.class,
    ProjectionsRelStructure.class,
    OnlineServicesRelStructure.class,
    RollingStockItemsRelStructure.class,
    OrganisationsInFrameRelStructure.class,
    StopPlaceVehicleEntrancesRelStructure.class,
    SpotRowsRelStructure.class,
    VehicleMeetingPointAssignmentsRelStructure.class,
    CheckConstraintInFrameRelStructure.class,
    SpotAffinitiesRelStructure.class,
    ComplexFeatureMembersRelStructure.class,
    JourneysInFrameRelStructure.class,
    LinesInFrameRelStructure.class,
    GeneralSectionsInFrameRelStructure.class,
    ResponsibilitySetsRelStructure.class,
    CheckConstraintDelaysInFrameRelStructure.class,
    LuggageSpotsRelStructure.class,
    MobilityServiceConstraintZonesInFrameRelStructure.class,
    VehicleServicesInFrameRelStructure.class,
    FareContractsRelStructure.class,
    ParkingLogEntriesInFrameRelStructure.class,
    ParkingChargeBandsRelStructure.class,
    ServiceExclusionsInFrameRelStructure.class,
    ReliefOpportunitiesInFrameRelStructure.class,
    DeckWindowsRelStructure.class,
    GroupsOfSitesRelStructure.class,
    TransferRestrictionsInFrameRelStructure.class,
    JourneyPartsInFrameRelStructure.class,
    TravelSpecificationsRelStructure.class,
    MobilityServicesRelStructure.class,
    TopographicPlacesInFrameRelStructure.class,
    TypesOfSecurityListRelStructure.class,
    CrewBasesInFrameRelStructure.class,
    FlexibleAreasRelStructure.class,
    TypesOfAccountStatusRelStructure.class,
    AccessZonesRelStructure.class,
    CodespacesInFrameRelStructure.class,
    RechargingPointAssignmentsRelStructure.class,
    AcceptedDriverPermitsRelStructure.class,
    ActualVehicleEquipmentsRelStructure.class,
    DistributionAssignmentsRelStructure.class,
    SitePathLinksInFrameRelStructure.class,
    PassengerEquipmentsRelStructure.class,
    PassengerSpotAllocationsRelStructure.class,
    DeckSpacesRelStructure.class,
    VersionFrameMembersRelStructure.class,
    LineNetworksInFrameRelStructure.class,
    JourneyPatternsInFrameRelStructure.class,
    EntitiesInVersionRelStructure.class,
    OccupancyViewRelStructure.class,
    TransportOperatorsInFrameRelStructure.class,
    ContractsInFrameRelStructure.class,
    JourneyAccountingsRelStructure.class,
    TimingPointsInFrameRelStructure.class,
    TypesOfMachineReadabilitiesRelStructure.class,
    RoutesRelStructure.class,
    FlexibleQuaysRelStructure.class,
    VehicleStoppingPlacesRelStructure.class,
    SiteFacilitySetsRelStructure.class,
    RechargingStationsRelStructure.class,
    FlexibleLinkPropertiesRelStructure.class,
    GroupsOfTariffZonesInFrameRelStructure.class,
    PoolOfVehiclesRelStructure.class,
    InterchangeRuleFiltersRelStructure.class,
    ParkingCapacitiesRelStructure.class,
    VehicleTypeStopAssignmentsRelStructure.class,
    RoutesInFrameRelStructure.class,
    GroupOfTimebandsInFrameRelStructure.class,
    DeckPathLinkRefsRelStructure.class,
    VehicleMeetingPointsInFrameRelStructure.class,
    ExplicitPlaceEquipmentsRelStructure.class,
    StopPlacesRelStructure.class,
    FacilityRequirementsRelStructure.class,
    ScheduledStopPointsInFrameRelStructure.class,
    FlexibleStopPlacesInFrameRelStructure.class,
    RestrictedServiceFacilitySetsInFrameRelStructure.class,
    ReliefOpportunitiesRelStructure.class,
    SiteEntrancesRelStructure.class,
    TypeOfConcessionsRelStructure.class,
    ServiceBookingArrangementsRelStructure.class,
    TypesOfFacilityRelStructure.class,
    VehiclePositionAlignmentsRelStructure.class,
    DayTypesRelStructure.class,
    FareStructureFactorsRelStructure.class,
    JourneyAccountingsInFrameRelStructure.class,
    GeographicalIntervalsRelStructure.class,
    NoticeAssignmentsRelStructure.class,
    NoticeAssignmentViewsRelStructure.class,
    NavigationPathsRelStructure.class,
    CustomerAccountsRelStructure.class,
    ParkingAreasRelStructure.class,
    BlocksInFrameRelStructure.class,
    FulfilmentMethodsRelStructure.class,
    WhitelistsRelStructure.class,
    GroupOfTimingLinksInFrameRelStructure.class,
    ContactsRelStructure.class,
    ResponsibilityRolesInFrameRelStructure.class,
    SiteFacilitySetsInFrameRelStructure.class,
    JourneyMeetingsInFrameRelStructure.class,
    CoursesOfJourneysRelStructure.class,
    FlexibleStopPlacesRelStructure.class,
    DisplayAssignmentsRelStructure.class,
    LineSectionsRelStructure.class,
    PassengerSpotsRelStructure.class,
    EquipmentsInFrameRelStructure.class,
    SiteStructuresRelStructure.class,
    RelatedOrganisationsRelStructure.class,
    LocalServicesRelStructure.class,
    CoursesOfJourneysInFrameRelStructure.class,
    DayTypesInFrameRelStructure.class,
    DepartmentsInFrameRelStructure.class,
    ValidityParameterAssignmentsRelStructure.class,
    BookingArrangementsInFrameRelStructure.class,
    PointOfInterestClassificationHierarchiesInFrameRelStructure.class,
    RollingStockInventoriesRelStructure.class,
    ExplicitEquipmentsRelStructure.class,
    PointOfInterestSpacesRelStructure.class,
    DistanceMatrixElementsRelStructure.class,
    InfrastructureJunctionsInFrameRelStructure.class,
    VehicleJourneyStopAssignmentsRelStructure.class,
    DisplayAssignmentsInFrameRelStructure.class,
    VehicleStoppingPositionsRelStructure.class,
    AccessSpacesRelStructure.class,
    GroupsOfDistanceMatrixElementsRelStructure.class,
    TimingPointsRelStructure.class,
    JourneyInterchangesInFrameRelStructure.class,
    PlaceEquipmentsRelStructure.class,
    BlacklistsRelStructure.class,
    ServiceLinksInFrameRelStructure.class,
    GaragesInFrameRelStructure.class,
    TransfersInFrameRelStructure.class,
    CustomerPaymentMeansRelStructure.class,
    RechargingBaysRelStructure.class,
    TaxiRanksInFrameRelStructure.class,
    LevelsInStructureRelStructure.class,
    PassengerJourneysInFrameRelStructure.class,
    GeneralPathJunctionRefsRelStructure.class,
    OnboardStaysRelStructure.class,
    PointsOfInterestInFrameRelStructure.class,
    EntityInVersionInFrameRelStructure.class,
    FarePointsInPatternRelStructure.class,
    BoardingPositionsRelStructure.class,
    SpotColumnsRelStructure.class,
    ResponsibilitySetsInFrameRelStructure.class,
    ParkingTariffsInFrameRelStructure.class,
    ModesOfOperationRelStructure.class,
    ReplacedJourneysRelStructure.class,
    RoutePointsInFrameRelStructure.class,
    AdministrativeZonesRelStructure.class,
    VehicleQuayAlignmentsRelStructure.class,
    NetworksInFrameRelStructure.class,
    AccessesRelStructure.class,
    InterchangeRulesInFrameRelStructure.class,
    TransportModesRelStructure.class,
    PassengerVehicleSpotsRelStructure.class,
    TrainComponentStopAssignmentsRelStructure.class,
    TaxiStandsRelStructure.class,
    VehicleEntrancesRelStructure.class,
    ZonesInFrameRelStructure.class,
    ParkingLogEntriesRelStructure.class,
    FlexibleServicePropertiesInFrameRelStructure.class,
    SpatialFeaturesInFrameRelStructure.class,
    DutyPartsRelStructure.class,
    VehicleTypesInFrameRelStructure.class,
    FareStructureElementsRelStructure.class,
    TimeDemandTypeAssignmentsInFrameRelStructure.class,
    PointsOnLinkInFrameRelStructure.class,
    TimeUnitsRelStructure.class,
    DirectionsInFrameRelStructure.class,
    CommonSectionsInFrameRelStructure.class,
    TrainComponentLabelAssignmentsRelStructure.class,
    PointOfInterestClassificationsInFrameRelStructure.class,
    SpecialServicesRelStructure.class,
    VehicleAccessCredentialAssignmentsRelStructure.class,
    OccupancyViewInFrameRelStructure.class,
    VehicleJourneySpotAllocationsRelStructure.class,
    SalesTransactionsRelStructure.class,
    DestinationDisplaysInFrameRelStructure.class,
    TimeIntervalsRelStructure.class,
    EquipmentPlacesRelStructure.class,
    JourneyPartPositionsRelStructure.class,
    AccommodationsRelStructure.class,
    SubmodesRelStructure.class,
    CountriesInFrameRelStructure.class,
    GroupOfLinksInFrameRelStructure.class,
    PurposesOfGroupingInFrameRelStructure.class,
    TariffZonesInFrameRelStructure.class,
    OperatingPeriodsInFrameRelStructure.class,
    DataSourcesRelStructure.class,
    AvailabilityConditionsRelStructure.class,
    PriceUnitsRelStructure.class,
    OperationalContextsInFrameRelStructure.class,
    VersionsRelStructure.class,
    NoticesRelStructure.class,
    FlexiblePointPropertiesRelStructure.class,
    ParkingsInFrameRelStructure.class,
    ParkingEntrancesForVehiclesRelStructure.class,
    DriverTripsInFrameRelStructure.class,
    NoticesInFrameRelStructure.class,
    JourneyPartCouplesInFrameRelStructure.class,
    PassengerCarryingRequirementsRelStructure.class,
    TimebandsRelStructure.class,
    CheckConstraintsRelStructure.class,
    JourneyPartCouplesRelStructure.class,
    DeckEntrancesRelStructure.class,
    OperatingDaysInFrameRelStructure.class,
    OpenModesRelStructure.class,
    TypeOfUsageParametersRelStructure.class,
    LinesInDirectionRefsRelStructure.class,
    NoticeAssignmentsInFrameRelStructure.class,
    StopPlacesInFrameRelStructure.class,
    VehicleTypeZoneRestrictionsRelStructure.class,
    GroupsOfOperatorsInFrameRelStructure.class,
    PointOfInterestEntrancesRelStructure.class,
    CustomerEligibilitiesRelStructure.class,
    SalesOfferPackageElementsRelStructure.class,
    SecurityListingsRelStructure.class,
    SpecificParameterAssignmentsRelStructure.class,
    PointOnLineSectionsRelStructure.class,
    PassengerInformationEquipmentsInFrameRelStructure.class,
    PassengerSpacesRelStructure.class,
    SecurityListsRelStructure.class,
    GenericParameterAssignmentsRelStructure.class,
    GeographicalUnitsRelStructure.class,
    AccessesInFrameRelStructure.class,
    LogicalDisplaysInFrameRelStructure.class,
    DepartmentsRelStructure.class,
    VersionsInFrameRelStructure.class,
    TypeOfAccessRightAssignmentsRelStructure.class,
    VehiclesRelStructure.class,
    CheckConstraintThroughputsInFrameRelStructure.class,
    RouteLinksInFrameRelStructure.class,
    ModeRestrictionAssessmentsRelStructure.class,
    ValidityRuleParametersRelStructure.class,
    BlockPartsRelStructure.class,
    GroupsOfServicesInFrameRelStructure.class,
    DayTypeAssignmentsInFrameRelStructure.class,
    DeckLevelsRelStructure.class,
    GroupsOfStopPlacesInFrameRelStructure.class,
    VehicleManoeuvringRequirementsRelStructure.class,
    FareContractEntriesRelStructure.class,
    OrganisationalUnitsRelStructure.class,
    ValidityTriggersRelStructure.class,
    IndividualPassengerInfosRelStructure.class,
    ControlCentresInFrameRelStructure.class,
    CompatibleEquipmentRefsRelStructure.class,
    MobilityServiceConstraintZonesRelStructure.class,
    TimeDemandTypesInFrameRelStructure.class,
    FleetsRelStructure.class,
    HailAndRideAreasRelStructure.class,
    NetworkRestrictionsInFrameRelStructure.class,
    NavigationPathsInFrameRelStructure.class,
    DeckEntranceAssignmentsRelStructure.class,
    DutiesInFrameRelStructure.class,
    GeneralFrameMembersRelStructure.class,
    TypesOfCustomerAccountRelStructure.class,
    PathInstructionsRelStructure.class,
    TrainNumbersInFrameRelStructure.class,
    DriverTripTimesRelStructure.class,
    TopographicPlacesRelStructure.class,
    TypesOfValueInFrameRelStructure.class,
    GroupOfEntitiesInFrameRelStructure.class,
    CoupledJourneysRelStructure.class,
    OrganisationPartsRelStructure.class,
    VehicleMeetingPointsRelStructure.class,
    RechargingPlansRelStructure.class,
    ServiceFacilitySetsInFrameRelStructure.class,
    InfrastructureElementsInFrameRelStructure.class,
    TrafficControlPointsInFrameRelStructure.class,
    SchematicMapsInFrameRelStructure.class,
    CustomersRelStructure.class,
    CustomerPurchasePackageElementsRelStructure.class,
    DutyPartsInFrameRelStructure.class,
    ResponsibilityRolesRelStructure.class,
    RestrictedServiceFacilitySetsRelStructure.class,
    VehicleMeetingPlacesRelStructure.class,
    VehicleServicePartsRelStructure.class,
    TimingLinksInFrameRelStructure.class,
    AllowedLineDirectionsRelStructure.class,
    ExplicitLocalServicesRelStructure.class,
    SeriesConstraintsRelStructure.class,
    IndividualTravellersRelStructure.class,
    SitePathLinksRelStructure.class,
    SalesOfferPackageSubstitutionsRelStructure.class,
    TypesOfRetailDeviceRelStructure.class,
    FareSectionsRelStructure.class,
    DefaultInterchangesInFrameRelStructure.class,
    RetailConsortiumsRelStructure.class,
    VehicleModelsInFrameRelStructure.class,
    TypesOfTravelDocumentsRelStructure.class,
    PassengerBoardingPositionAssignmentsRelStructure.class,
    InterchangeRulesRelStructure.class,
    GroupsOfPlacesInFrameRelStructure.class,
    VehicleModelProfilesInFrameRelStructure.class,
    TrainComponentsRelStructure.class
})
public class ContainmentAggregationStructure
    extends RelationshipStructure
{

    @XmlAttribute(name = "modificationSet")
    protected ModificationSetEnumeration modificationSet;

    /**
     * Ruft den Wert der modificationSet-Eigenschaft ab.
     * 
     * @return
     *     possible object is
     *     {@link ModificationSetEnumeration }
     *     
     */
    public ModificationSetEnumeration getModificationSet() {
        if (modificationSet == null) {
            return ModificationSetEnumeration.ALL;
        } else {
            return modificationSet;
        }
    }

    /**
     * Legt den Wert der modificationSet-Eigenschaft fest.
     * 
     * @param value
     *     allowed object is
     *     {@link ModificationSetEnumeration }
     *     
     */
    public void setModificationSet(ModificationSetEnumeration value) {
        this.modificationSet = value;
    }

}
